import { mkdirSync, readFileSync, watchFile, writeFileSync } from "node:fs";

const inputFile = "src/components/style.css";
const outputDir = "src/generated";
const outputFile = `${outputDir}/styles.ts`;

async function generate() {
  // @ts-expect-error top-level postcss import
  const postcss = (await import("postcss")).default;
  // @ts-expect-error tailwind postcss plugin
  const tailwind = (await import("@tailwindcss/postcss")).default;
  const cssFile = readFileSync(inputFile, "utf8");
  const result = await postcss([tailwind()]).process(Buffer.from(cssFile), {
    from: inputFile,
    to: undefined,
    map: false,
  });
  mkdirSync(outputDir, { recursive: true });
  writeFileSync(outputFile, `/* Generated by scripts/gen-styles.ts — do not edit */\nexport default ${JSON.stringify(result.css)};\n`);
  console.log(`✓ generated ${outputFile} (${result.css.length} bytes)`);
}

const watch = process.argv.includes("--watch");

if (watch) {
  console.log(`watching ${inputFile}…`);
  watchFile(inputFile, { interval: 200 }, () => {
    generate().catch((err) => {
      console.error("gen-styles failed:", err);
    });
  });
}

generate().catch((err) => {
  console.error("gen-styles failed:", err);
  process.exitCode = 1;
});